"""
dashboard/components/final_response_panel.py

Final business response panel.

This component renders the business-facing final response generated by the
workflow. It intentionally hides internal technical metadata such as:
- LLM used
- response source
- prompt/source mode

Those details remain available in the Raw State tab if needed for debugging,
but they are not shown in the main executive dashboard view.
"""

from typing import Any, Dict

import streamlit as st

from dashboard.utils.state_helpers import as_dict


def render_final_response_panel(result: Dict[str, Any]) -> None:
    """
    Renders the final business response section.

    The section shows:
    - Natural language business explanation
    - Expandable full markdown response

    It does not show internal LLM/debug metadata.
    """

    final_response_output = as_dict(result.get("final_response_output"))

    natural_language_explanation = final_response_output.get(
        "natural_language_explanation"
    )

    final_response_markdown = result.get("final_response")

    st.divider()
    st.subheader("Final Business Response")

    if natural_language_explanation:
        st.markdown("### Natural Language Explanation")
        st.write(natural_language_explanation)
    else:
        st.info("No natural language explanation generated.")

    with st.expander("View full final response markdown", expanded=False):
        st.markdown(final_response_markdown or "No final response available.")